import React from 'react';

interface PrintLayoutProps {
  pages: React.ReactElement[];
  headerTexts: {
    name: string;
    title: string;
  };
}

const PrintLayout: React.FC<PrintLayoutProps> = ({ pages, headerTexts }) => {
  return (
    <div className="print-container">
      {pages.map((Page, index) => (
        <section key={index} className="print-page">
          <header className="print-header no-print">
            {headerTexts.name} &middot; {headerTexts.title}
          </header>
          
          <div className="print-content">
            {Page}
          </div>

          <footer className="print-footer no-print">
            {/* Content for the footer (like page number) is generated by CSS */}
          </footer>
        </section>
      ))}
    </div>
  );
};

export default PrintLayout;